### ISSUE TITLE
canot edit members list 

### ISSUE THREAD

**Issue by anushka912** [RotaractIndia/pranali_reloaded#1]
Hey Neil ,
I have been trying to edit the member list on pronely but i dont have the option . All i see is no members founds .
is it because my user id  does not support addition of members 
Also what is the use of tags and what are they for ? 

Thank you

**Comment by neilLasrado** [comment]
@anushka912 President and Secretaries are not allowed to add or remove member details. However you can update details of existing members. Members will appear under the member section once you pay their district dues. It may take upto 7 days for us to upload the details on receiving the dues.

tags can be used to organise your project reports. check this help article on tags https://support.apple.com/en-us/HT202754. Just imagine reports instead of FIles.
